version: "3"

services:
  stan:
    image: nats-streaming:0.25.5
    ports:
      - ${NATS_STREAMING_PORT}:${NATS_STREAMING_PORT}
    restart: unless-stopped

  postgres:
    image: postgres:15.4
    volumes:
      - pg-data:/var/lib/postgresql/data
    env_file:
      - .env
    restart: unless-stopped
    ports:
      - "5433:5432"
    healthcheck:
      test: "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"
      interval: 10s
      timeout: 3s
      retries: 5

  migrate:
    image: migrate/migrate
    volumes:
      - ./migrations:/migrations
    command: [ "-path", "/migrations", "-database", "${MIGRATION_DB_URL}", "up" ]
    links:
      - postgres
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  pg-data:
